module.exports = [
    {
        mobo: "Asus TUF GAMING X570-PLUS (WI-FI)",
        cpu: "Intel Core i9-13900K",
        gpu: "Asus ROG STRIX GAMING OC",
        memory: "G.Skill Trident Z5 RGB 64 GB",
        storage: "Samsung 990 Pro",
        fan: "NZXT Kraken Z73 RGB",
        psu:"Corsair RM1000x (2021)",
        housing: "Lian Li O11 Dynamic EVO",
        price: 3909,
        imgURL: "https://cdna.pcpartpicker.com/static/forever/images/product/ea0dee3c3376cc6326ca2f4a73a054ac.256p.jpg",
        name: "Asus Premium Build",
        category: "Premium",
        author: "employee",
    },
    {
        mobo: "MSI MAG B660 TOMAHAWK WIFI DDR4",
        cpu: "AMD Ryzen 7 7800X3D",
        gpu: "MSI GAMING X TRIO",
        memory: "G.Skill Trident Z5 RGB 64 GB",
        storage: "Samsung 990 Pro",
        fan: "NZXT Kraken Z73 RGB",
        psu:"Corsair RM1000x (2021)",
        housing: "Corsair iCUE 4000X RGB",
        price: 2750,
        imgURL: "https://cdna.pcpartpicker.com/static/forever/images/product/0610d363ccccf52837f07d811e4eb2a3.256p.jpg",
        name: "MSI Standard Gaming Build",
        category: "Gaming",
        author: "employee",
    },
    {
        mobo: "Asus Prime B450M-A II",
        cpu: "Intel Core i5-12400F",
        gpu: "Asus DUAL",
        memory: "Corsair Vengeance LPX 16 GB",
        storage: "Kingston NV2",
        fan: "Thermalright Peerless Assassin 120 SE",
        psu:"Thermaltake Smart BM2",
        housing: "Thermaltake Versa H18",
        price: 1041,
        imgURL: "https://m.media-amazon.com/images/I/51BARwNk2iL.jpg",
        name: "Beginner Asus Build",
        category: "Budget",
        author: "employee",
    },
    {
        mobo: "MSI B550M PRO-VDH WIFI",
        cpu: "AMD Ryzen 5 5600",
        gpu: "MSI GeForce RTX 3060 Gaming X12G",
        memory: "Corsair Vengeance LPX 16 GB",
        storage: "Kingston NV2",
        fan: "Thermalright Peerless Assassin 120 SE",
        psu:"Thermaltake Smart BM2",
        housing: "Phanteks Eclipse P300A Mesh",
        price: 857,
        imgURL: "https://cdna.pcpartpicker.com/static/forever/images/product/7c9e187b65ab4b281bc2ca0fe41a9aa7.256p.jpg",
        name: "Beginner MSI Build",
        category: "Budget",
        author: "employee",
    },
    {
        mobo: "Gigabyte Z790 AORUS ELITE AX",
        cpu: "Intel Core i9-13900K",
        gpu: "Gigabyte GAMING OC",
        memory: "G.Skill Trident Z5 RGB 64 GB",
        storage: "Samsung 990 Pro",
        fan: "NZXT Kraken Z73 RGB",
        psu:"Corsair RM1000x (2021)",
        housing: "NZXT H510",
        price: 3909,
        imgURL: "https://cdna.pcpartpicker.com/static/forever/images/product/ea0dee3c3376cc6326ca2f4a73a054ac.256p.jpg",
        name: "Standard Gigabyte Gaming Build",
        category: "Gaming",
        author: "employee",
    },
    {
        mobo: "MSI B550M PRO-VDH WIFI",
        cpu: "AMD Ryzen 7 5800X",
        gpu: "ASRock Challenger D",
        memory: "Corsair Vengeance LPX 32 GB",
        storage: "Samsung 870 Evo",
        fan: "Thermalright Peerless Assassin 120 SE",
        psu:"Thermaltake Smart BM2",
        housing: "Thermaltake Versa H18",
        price: 795,
        imgURL: "https://m.media-amazon.com/images/I/51BARwNk2iL.jpg",
        name: "Above Average Business Computer",
        category: "Business",
        author: "employee",
    },
    {
        mobo: "Asus TUF GAMING X570-PLUS (WI-FI)",
        cpu: "Intel Core i9-13900K",
        gpu: "NVIDIA Founders Edition",
        memory: "G.Skill Trident Z5 RGB 64 GB",
        storage: "Samsung 990 Pro",
        fan: "NZXT Kraken Z73 RGB",
        psu:"Corsair RM1000x (2021)",
        housing: "Lian Li O11 Dynamic EVO",
        price: 3996,
        imgURL: "https://m.media-amazon.com/images/I/41EN5WjnfyL.jpg",
        name: "NVIDIA Premium Build",
        category: "Premium",
        author: "employee",
    },

]